### ISSUE TITLE
Multiple Galleries on Same Page

### ISSUE THREAD

**Issue by Brendan1983** [seyDoggy/superbox#3]
I'm just curious if you could point out how you allowed multiple galleries to open independently on the same page.  I altered Todd's version a bit so that I could insert text in along with the image when opened.  I'd like to have two of my modified Superbox galleries on the same page, but don't need all the great capabilities you've added on, so it would be awesome to find out how you did that.  Right now they both work, but the close button on the second does not.  You can see a demo <a href="http://brilliant-graphics.com/BrilliantJune2013">here</a>, the superbox galleries are the 'Services' and 'About' sections.

**Comment by seyDoggy** [comment]
It would be tough to pinpoint the differences since my version actually includes very little of the original code (maybe a line or two, that's it).  

## If your looking, then commit 178e1028 would be the place.

Adam Merrifield
seyDoggy vCard: seyDoggy.com/vcard

**Comment by Brendan1983** [comment]
Oh ok, well thanks for looking into this anyways.  I'll take a look at that commit.

**Comment by seyDoggy** [comment]
Check out the DIFF on js/jquery.superbox.js on that commit. Lots of useful info there.

## 

Adam Merrifield
seyDoggy vCard: seydoggy.com/vcard
